./build/bin/llama-quantize ./gemma-2b.gguf ./mymodel/gemma-2b-Q8_0.gguf Q8_0
./build/bin/llama-quantize ./gemma-2b.gguf ./mymodel/gemma-2b-Q6_K.gguf Q6_K
./build/bin/llama-quantize ./gemma-2b.gguf ./mymodel/gemma-2b-Q5_K.gguf Q5_K
./build/bin/llama-quantize ./gemma-2b.gguf ./mymodel/gemma-2b-Q4_K.gguf Q4_K
./build/bin/llama-quantize ./gemma-2b.gguf ./mymodel/gemma-2b-Q3_K.gguf Q3_K
./build/bin/llama-quantize ./gemma-2b.gguf ./mymodel/gemma-2b-Q2_K.gguf Q2_K
./build/bin/llama-quantize ./gemma-7b.gguf ./mymodel/gemma-7b-Q8_0.gguf Q8_0
./build/bin/llama-quantize ./gemma-7b.gguf ./mymodel/gemma-7b-Q6_K.gguf Q6_K
./build/bin/llama-quantize ./gemma-7b.gguf ./mymodel/gemma-7b-Q5_K.gguf Q5_K
./build/bin/llama-quantize ./gemma-7b.gguf ./mymodel/gemma-7b-Q4_K.gguf Q4_K
./build/bin/llama-quantize ./gemma-7b.gguf ./mymodel/gemma-7b-Q3_K.gguf Q3_K
./build/bin/llama-quantize ./gemma-7b.gguf ./mymodel/gemma-7b-Q2_K.gguf Q2_K